theme = "github_dark"

[editor]
line-number = "absolute"
mouse = false
auto-completion = true
path-completion = true
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

